import { Inter } from "next/font/google";
// import "./globals.css";
import { AppBar } from "@mui/material";
import Navbar from "@/components/shared/Navbar";
import Page from "@/components/pageSection/products/page"
import "./style/global.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
<Navbar/>
        {children}</body>
    </html>
  );
}
